project_id = "fnnoxdrkslfuuuuyltsr"

[functions.setup-installation-database]
verify_jwt = false

[functions.create-installation-admin]
verify_jwt = false

[functions.configure-installation-email]
verify_jwt = false

[functions.complete-installation]
verify_jwt = false
